### ISSUE TITLE
Ticking player NPE on lead Breaking event

### ISSUE THREAD

**Issue by Lothrazar** [Plutosion/Leashed#10]
Was flying around and chunks were loading & unloading when this happened

`java.lang.NullPointerException: Ticking player
	at plutosion.leashed.handler.LeadHandler.leadBreaking(LeadHandler.java:78) ~[leashed:1.2.0] {re:classloading}`

Full log https://pastebin.com/hsRy2EH7

**Comment by Mrbysco** [comment]
Should be fixed in 1.2.1
