### ISSUE TITLE
Game crashes when tethering more than one animal and attempting to use elytra

### ISSUE THREAD

**Issue by machandler318** [Plutosion/Leashed#8]
![aaaaaa](https://user-images.githubusercontent.com/60990425/115079379-f153c400-9eb5-11eb-92b9-04d4a52725f6.PNG)
[Crashreport.txt](https://github.com/Plutosion/Leashed/files/6327681/Crashreport.txt)

The moment I hit shift for elytra, is crashed. here is the last frame

**Comment by machandler318** [comment]
I am running no mods but this on 1.16.5. Using recommended version of forge, but was able to replicate on latest version of forge for 1.16.5

**Comment by Mrbysco** [comment]
The crash report has nothing to do with leashed. The crash is you running out of memory. Are you sure you have enough memory allocated?
